version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web1:
    build: ./pipeline_creation
    command: ./docker-entrypoint.sh
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DATALINE_URL1=http://0.0.0.0:8001
      - DATALINE_URL2=http://0.0.0.0:8002
    depends_on:
      - db
  web2:
    build: ./pipeline_execution
    command: ./docker-entrypoint.sh
    ports:
      - "8002:8002"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DATALINE_URL1=http://0.0.0.0:8001
      - DATALINE_URL2=http://0.0.0.0:8002
    depends_on:
      - db