# Generated by Django 4.0.2 on 2022-03-17 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_pipeline_timestamp_pipeline_updated_stage_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
