# Generated by Django 4.0.2 on 2022-03-17 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_pipeline_pipeline_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='stage',
        ),
        migrations.AddField(
            model_name='operation',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.pipeline'),
        ),
        migrations.AddField(
            model_name='operation',
            name='stage_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
