# Generated by Django 3.2.12 on 2022-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_remove_operation_stage_operation_pipeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_name',
            field=models.IntegerField(choices=[(1, 'Lower Case'), (2, 'Upper Case'), (3, 'Add Value'), (4, 'Multiply Value'), (5, 'Divide Value'), (6, 'Add Columns'), (7, 'Multiply Columns'), (8, 'Divide Columns'), (9, 'Length of Text'), (10, 'Date Difference'), (11, 'Add Date'), (12, 'Split Column by delimiter')], default=1),
        ),
    ]
