# Generated by Django 3.2.12 on 2022-03-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_alter_operation_operation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_name',
            field=models.CharField(choices=[('Lower Case', 'Lower Case'), ('Upper Case', 'Upper Case'), ('Add Value', 'Add Value'), ('Multiply Value', 'Multiply Value'), ('Divide Value', 'Divide Value'), ('Add Columns', 'Add Columns'), ('Multiply Columns', 'Multiply Columns'), ('Divide Columns', 'Divide Columns'), ('Length of Text', 'Length of Text'), ('Date Difference', 'Date Difference'), ('Add Date', 'Add Date'), ('Split Column by delimiter', 'Split Column by delimiter')], max_length=100),
        ),
    ]
