# Generated by Django 3.2.12 on 2022-03-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_alter_operation_operation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='column_name',
        ),
    ]
