# Generated by Django 3.2.12 on 2022-03-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_remove_operation_column_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='data_input_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operation',
            name='data_output_name',
            field=models.CharField(max_length=100),
        ),
    ]
