# Generated by Django 3.2.12 on 2022-03-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0009_auto_20220320_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='stage_name',
            field=models.CharField(max_length=100),
        ),
    ]
