OPERATION_CHOICES = (
    ("Lower Case", "Lower Case"),
    ("Upper Case", "Upper Case"),
    ("Add Value", "Add Value"),
    ("Multiply Value", "Multiply Value"),
    ("Divide Value", "Divide Value"),
    ("Add Columns", "Add Columns"),
    ("Multiply Columns", "Multiply Columns"),
    ("Divide Columns", "Divide Columns"),
    ("Length of Text", "Length of Text"),
    ("Date Difference", "Date Difference"),
    ("Add Date", "Add Date"),
    ("Split Column by delimiter", "Split Column by delimiter"),
    ("Join Tables", "Join Tables"),
    ("Rename Column", "Rename Column"),
    ("Delete Column", "Delete Column"),
    ("Integer Filter", "Integer Filter"),
    ("Delete Duplicate rows", "Delete Duplicate rows"),
    ("RegEx filter", "RegEx filter"),
    ("Append Tables", "Append Tables"),
  )